/*
* Licensed Materials - Property of IBM
* (C) Copyright IBM Corp. 2016. All Rights Reserved.
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
*/
'use strict';

var _ = require('lodash');
var HUBOT_IBMCLOUD_POWERUSERS = process.env.HUBOT_IBMCLOUD_POWERUSERS;
var HUBOT_IBMCLOUD_READERUSERS = process.env.HUBOT_IBMCLOUD_READERUSERS;
var HUBOT_IBMCLOUD_LDAP_PROTOCOL = process.env.HUBOT_IBMCLOUD_LDAP_PROTOCOL;
var HUBOT_IBMCLOUD_LDAP_SERVER = process.env.HUBOT_IBMCLOUD_LDAP_SERVER;
var HUBOT_IBMCLOUD_LDAP_PORT = process.env.HUBOT_IBMCLOUD_LDAP_PORT;
var HUBOT_IBMCLOUD_LDAP_BIND_USER = process.env.HUBOT_IBMCLOUD_LDAP_BIND_USER;
var HUBOT_IBMCLOUD_LDAP_BIND_PASSWORD = process.env.HUBOT_IBMCLOUD_LDAP_BIND_PASSWORD;
var HUBOT_IBMCLOUD_LDAP_ORG_ROOT = process.env.HUBOT_IBMCLOUD_LDAP_ORG_ROOT;
var HUBOT_IBMCLOUD_LDAP_EMAIL_FIELD = process.env.HUBOT_IBMCLOUD_LDAP_EMAIL_FIELD;
var HUBOT_IBMCLOUD_LDAP_GROUP_MEMBERSHIP_FIELD = process.env.HUBOT_IBMCLOUD_LDAP_GROUP_MEMBERSHIP_FIELD;
var HUBOT_IBMCLOUD_LDAP_POWERUSERS_GROUP_DN_LIST = process.env.HUBOT_IBMCLOUD_LDAP_POWERUSERS_GROUP_DN_LIST;
var HUBOT_IBMCLOUD_LDAP_READERUSERS_GROUP_DN_LIST = process.env.HUBOT_IBMCLOUD_LDAP_READERUSERS_GROUP_DN_LIST;
var HUBOT_IBMCLOUD_AUTHENTICATION_DISABLED = process.env.HUBOT_IBMCLOUD_AUTHENTICATION_DISABLED;

if (_.isString(HUBOT_IBMCLOUD_POWERUSERS)) {
	HUBOT_IBMCLOUD_POWERUSERS = HUBOT_IBMCLOUD_POWERUSERS.trim();
}
if (_.isString(HUBOT_IBMCLOUD_READERUSERS)) {
	HUBOT_IBMCLOUD_READERUSERS = HUBOT_IBMCLOUD_READERUSERS.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_PROTOCOL)) {
	HUBOT_IBMCLOUD_LDAP_PROTOCOL = HUBOT_IBMCLOUD_LDAP_PROTOCOL.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_SERVER)) {
	HUBOT_IBMCLOUD_LDAP_SERVER = HUBOT_IBMCLOUD_LDAP_SERVER.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_PORT)) {
	HUBOT_IBMCLOUD_LDAP_PORT = HUBOT_IBMCLOUD_LDAP_PORT.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_BIND_USER)) {
	HUBOT_IBMCLOUD_LDAP_BIND_USER = HUBOT_IBMCLOUD_LDAP_BIND_USER.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_BIND_PASSWORD)) {
	HUBOT_IBMCLOUD_LDAP_BIND_PASSWORD = HUBOT_IBMCLOUD_LDAP_BIND_PASSWORD.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_ORG_ROOT)) {
	HUBOT_IBMCLOUD_LDAP_ORG_ROOT = HUBOT_IBMCLOUD_LDAP_ORG_ROOT.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_EMAIL_FIELD)) {
	HUBOT_IBMCLOUD_LDAP_EMAIL_FIELD = HUBOT_IBMCLOUD_LDAP_EMAIL_FIELD.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_GROUP_MEMBERSHIP_FIELD)) {
	HUBOT_IBMCLOUD_LDAP_GROUP_MEMBERSHIP_FIELD = HUBOT_IBMCLOUD_LDAP_GROUP_MEMBERSHIP_FIELD.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_POWERUSERS_GROUP_DN_LIST)) {
	HUBOT_IBMCLOUD_LDAP_POWERUSERS_GROUP_DN_LIST = HUBOT_IBMCLOUD_LDAP_POWERUSERS_GROUP_DN_LIST.trim();
}
if (_.isString(HUBOT_IBMCLOUD_LDAP_READERUSERS_GROUP_DN_LIST)) {
	HUBOT_IBMCLOUD_LDAP_READERUSERS_GROUP_DN_LIST = HUBOT_IBMCLOUD_LDAP_READERUSERS_GROUP_DN_LIST.trim();
}

const settings = {
	powerUsers: HUBOT_IBMCLOUD_POWERUSERS,
	readerUsers: HUBOT_IBMCLOUD_READERUSERS,
	ldapProtocol: HUBOT_IBMCLOUD_LDAP_PROTOCOL,
	ldapServer: HUBOT_IBMCLOUD_LDAP_SERVER,
	ldapPort: HUBOT_IBMCLOUD_LDAP_PORT,
	ldapBindUser: HUBOT_IBMCLOUD_LDAP_BIND_USER,
	ldapBindPassword: HUBOT_IBMCLOUD_LDAP_BIND_PASSWORD,
	ldapPowerGroups: HUBOT_IBMCLOUD_LDAP_POWERUSERS_GROUP_DN_LIST,
	ldapReaderGroups: HUBOT_IBMCLOUD_LDAP_READERUSERS_GROUP_DN_LIST,
	ldapOrgRoot: HUBOT_IBMCLOUD_LDAP_ORG_ROOT,
	ldapEmailField: HUBOT_IBMCLOUD_LDAP_EMAIL_FIELD,
	ldapGroupMembershipField: HUBOT_IBMCLOUD_LDAP_GROUP_MEMBERSHIP_FIELD,
	authenticationDisabled: HUBOT_IBMCLOUD_AUTHENTICATION_DISABLED
};

module.exports = settings;
